# Generated by Django 5.0.7 on 2024-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

 
    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                # Alan tanımları
            ],
        ),
        # Diğer işlemler
    ]
       