# Generated by Django 5.0.7 on 2024-07-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False},
        ),
    ]
