# Generated by Django 5.0.7 on 2024-07-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_region_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
    ]
