# Generated by Django 5.0.7 on 2024-07-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_region_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territories',
            fields=[
                ('territory_id', models.AutoField(primary_key=True, serialize=False)),
                ('territory_description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'territories',
                'managed': False,
            },
        ),
    ]
