# Generated by Django 5.0.7 on 2024-07-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_territories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('title_of_courtesy', models.CharField(max_length=25)),
                ('birth_date', models.DateField()),
                ('hire_date', models.DateField()),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=15)),
                ('region', models.CharField(blank=True, max_length=15, null=True)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=15)),
                ('home_phone', models.CharField(max_length=24)),
                ('extension', models.CharField(max_length=4)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('reports_to', models.IntegerField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeTerritories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'employee_territories',
                'managed': False,
            },
        ),
    ]
