# Generated by Django 5.0.7 on 2024-08-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_categories'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='Categories',
        ),
    ]
