# Generated by Django 5.0.7 on 2024-08-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_products_suppliers_alter_categories_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsStates',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255)),
                ('state_abbr', models.CharField(max_length=2)),
                ('state_region', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'us_states',
                'managed': False,
            },
        ),
    ]
