# Generated by Django 5.0.7 on 2024-08-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField()),
            ],
            options={
                'db_table': 'order_details',
                'managed': False,
            },
        ),
    ]
