# Generated by Django 5.0.7 on 2024-08-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDemographics',
            fields=[
                ('customer_type_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_demographics',
                'managed': False,
            },
        ),
    ]
