# Generated by Django 5.0.7 on 2024-08-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_customerdemographics'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCustomerDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'customer_customer_demo',
                'managed': False,
            },
        ),
    ]
